my:
  name: test
  age: 22
  number: 1
  uuid: 112233
  max: 223344
  value: "AAA"
  greeting: "Good"
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.protry.domain.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
